# This is a basic workflow to help you get started with Actions

name: CI

env:
  TZ: Asia/Shanghai

# Controls when the action will run.
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --immutable
      - run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} node ./dist/index.js
